package com.personal.agenda;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;

@DynamoDBTable(tableName = "Eventos")
public class Evento implements Serializable {

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Fecha")
    @DynamoDBTyped(value = DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    private Long fecha;

    @DynamoDBAttribute(attributeName = "Asunto")
    private String asunto;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Long getFecha() {
        return fecha;
    }

    public void setFecha(Long fecha) {
        this.fecha = fecha;
    }

    public String getAsunto() {
        return asunto;
    }

    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    @Override
    public String toString() {
        return "Evento{" +
                " Id ='" + id + '\'' +
                ", Fecha =" + fecha  +
                ", Asunto =" + asunto +
                '}';
    }
}